In [40]:
import tweepy,pymongo
import json
import pandas as pd

conskeys = ######Insert key
consecret = #####Insert secret
acctok = #####Insert token
acctoksecret = #####Insert secret token

# Authentication
auth = tweepy.OAuthHandler(conskeys, consecret)
auth.set_access_token(acctok, acctoksecret)
api = tweepy.API(auth)
query = "U.S. economy"

client = pymongo.MongoClient()
db = client["tweet_database"]
my_tweets_table = db.tweets_collection_final  # Setting collection to enter documents.

_max_queries = 175  # arbitrarily chosen value
tweet = tweet_batch = api.search(q=query, count=100,tweet_mode='extended')

for tweet in tweet_batch:
        tweets = []
        tweets.append((tweet.created_at,tweet.id,tweet.full_text,tweet.source, tweet.truncated, tweet.metadata,tweet.in_reply_to_status_id, tweet.in_reply_to_user_id, tweet.in_reply_to_screen_name,tweet.user._json, tweet.place,tweet.is_quote_status, tweet.retweet_count,tweet.favorite_count,tweet.entities,tweet.favorited,tweet.retweeted,tweet.lang))
        tweetsdf = pd.DataFrame(tweets,columns=['created_at', 'id', 'full_text', 'source', 'truncated','metadata','in_reply_to_status_id','in_reply_to_user_id','in_reply_to_screen_name', 'user','place','is_quote_status','retweet_count','favorite_count', 'entities','favorited','retweeted','lang'])
        tweetsdf.to_csv('Economy_USA_final.csv')
        id_ = tweet.id
        id_str = tweet.id_str
        user_id = tweet.user.id_str
        user_name = tweet.user.name
        user = tweet.user._json
        in_reply_to_user_id = tweet.in_reply_to_user_id
        lang = tweet.lang
        source = tweet.source
        retweet_count = tweet.retweet_count
        in_reply_to_status_id = tweet.in_reply_to_status_id
        lang = tweet.lang
        fav = tweet.favorite_count
        try:
            x = tweet.retweeted_status  
            retweetedFrom_id = x.user.id_str
            retweetedFrom_OrigTweetid = x.id
            retweetedFrom_name = x.user.screen_name
            RT = True
        except AttributeError:  
            retweetedFrom_id = -1
            retweetedFrom_name = 'NA'
            retweetedFrom_OrigTweetid = -1
            RT = False
        if RT:
            content = tweet.retweeted_status.full_text
            retweet_fav = tweet.retweeted_status.favorite_count
        else:
            content = tweet.full_text
            retweet_fav = -1
        created_at = str(tweet.created_at)
        location = tweet.user.location
        ht = tweet.entities["hashtags"]
        hashtags = []
        for i in ht:
            hashtags.append(i["text"]) # List of hashtags.
        mntn = tweet.entities["user_mentions"]
        mentions = []
        for i in mntn:
            mentions.append(i['id_str']) # List of mentions
        try:
            md = tweet.entities["media"]
            media = []
            for i in md:
                media.append(i["url"]) # And list of media (photos only)
        except KeyError:  # If no media found
            media = []
        try:
            jsonx = {"id":id_,"user_name": user_name, "user_id": user_id, "content": content, "created_at": created_at, "location": location,
            "hashtags": hashtags, "mentions": mentions, "in_reply_to_user_id": in_reply_to_user_id,"in_reply_to_status_id":in_reply_to_status_id,"retweedt_orid_tweetID": retweetedFrom_OrigTweetid,"retweetedFrom_id": retweetedFrom_id,"retweetedFrom_name": retweetedFrom_name, "media": media, "retweet": RT, "FavCount": fav,"Orig_retweet_fav":retweet_fav ,"source":source, "retweet_count":retweet_count, "lang":lang} # Making a JSON to be sent to collection.
            my_tweets_table.insert(jsonx)  # And insert
        except pymongo.errors.DuplicateKeyError as e:  # Except if it's already there
            print("Duplicate Key")

ct = 1
while ct < _max_queries:
    tweet_batch = api.search(q=query, 
                             count=100,
                             max_id=tweet_batch.max_id-1,tweet_mode='extended')
    
    for tweet in tweet_batch:
        tweets = []
        tweets.append((tweet.created_at,tweet.id,tweet.full_text,tweet.source, tweet.truncated, tweet.metadata, tweet.in_reply_to_status_id, tweet.in_reply_to_user_id, tweet.in_reply_to_screen_name, tweet.user._json, tweet.place,tweet.is_quote_status, tweet.retweet_count,tweet.favorite_count,tweet.entities,tweet.favorited,tweet.retweeted, tweet.lang ))
        tweetsdf = pd.DataFrame(tweets,columns=['created_at', 'id', 'full_text', 'source', 'truncated','metadata','in_reply_to_status_id','in_reply_to_user_id','in_reply_to_screen_name','user','place','is_quote_status','retweet_count','favorite_count','entities','favorited','retweeted','lang'])
        tweetsdf.to_csv('Economy_USA_final.csv', mode='a', header=False)
        id_ = tweet.id
        id_str = tweet.id_str
        user_id = tweet.user.id_str
        user_name = tweet.user.name
        user = tweet.user._json
        in_reply_to_user_id = tweet.in_reply_to_user_id
        lang = tweet.lang
        source = tweet.source
        retweet_count = tweet.retweet_count
        in_reply_to_status_id = tweet.in_reply_to_status_id
        lang = tweet.lang
        fav = tweet.favorite_count
        try:
            x = tweet.retweeted_status  
            retweetedFrom_id = x.user.id_str
            retweetedFrom_name = x.user.screen_name
            retweetedFrom_OrigTweetid = x.id
            RT = True
        except AttributeError:  
            retweetedFrom_id = -1
            retweetedFrom_name = 'NA'
            retweetedFrom_OrigTweetid = -1
            RT = False
        if RT:
            content = tweet.retweeted_status.full_text
            retweet_fav = tweet.retweeted_status.favorite_count
        else:
            content = tweet.full_text
            retweet_fav = -1
        created_at = str(tweet.created_at)
        location = tweet.user.location
        ht = tweet.entities["hashtags"]
        hashtags = []
        for i in ht:
            hashtags.append(i["text"]) # List of hashtags.
        mntn = tweet.entities["user_mentions"]
        mentions = []
        for i in mntn:
            mentions.append(i['id_str']) # List of mentions
        try:
            md = tweet.entities["media"]
            media = []
            for i in md:
                media.append(i["url"]) # And list of media (photos only)
        except KeyError:  # If no media found
            media = []
        try:
            jsonx = {"id":id_,"user_name": user_name, "user_id": user_id, "content": content, "created_at": created_at, "location": location,
            "hashtags": hashtags, "mentions": mentions, "in_reply_to_user_id": in_reply_to_user_id,"in_reply_to_status_id":in_reply_to_status_id,"retweedt_orid_tweetID": retweetedFrom_OrigTweetid,"retweetedFrom_id": retweetedFrom_id,"retweetedFrom_name": retweetedFrom_name, "media": media, "retweet": RT, "FavCount": fav,"Orig_retweet_fav":retweet_fav ,"source":source, "retweet_count":retweet_count, "lang":lang} # Making a JSON to be sent to collection.
            my_tweets_table.insert(jsonx)  # And insert
        except pymongo.errors.DuplicateKeyError as e:  # Except if it's already there
            print("Duplicate Key")
    ct += 1

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:77: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:141: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.

In [41]:
data = pd.read_csv("Economy_USA_final.csv")
data.head()

,Unnamed: 0,created_at,id,full_text,source,truncated,metadata,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,user,place,is_quote_status,retweet_count,favorite_count,entities,favorited,retweeted,lang
0,0,2020-04-29 18:05:38,1255558878403547136,FED SAYS IT IS COMMITTED TO USING ITS FULL RAN...,Twitter Web App,False,"{'iso_language_code': 'en', 'result_type': 're...",1.255559e+18,1.040666e+18,RedboxWire,"{'id': 1040665819187953664, 'id_str': '1040665...",NaN,False,1,4,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
1,0,2020-04-29 18:05:33,1255558857683804160,RT @CGTNOfficial: The Federal Reserve painted ...,Twitter for iPhone,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 498137972, 'id_str': '498137972', 'name...",NaN,False,4,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
2,0,2020-04-29 18:05:16,1255558785613074435,"THREAD—""The Federal Reserve is committed to us...",Twitter Web App,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 65466158, 'id_str': '65466158', 'name':...",NaN,False,3,3,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
3,0,2020-04-29 18:05:12,1255558770291335168,The U.S. Government Out Here Carring About It’...,Twitter for iPhone,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 1399854920, 'id_str': '1399854920', 'na...",NaN,False,0,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
4,0,2020-04-29 18:05:09,1255558756890374144,“The Federal Reserve said the U.S. economy has...,Twitter for iPhone,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 940032448057896960, 'id_str': '94003244...",NaN,False,0,1,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en

In [42]:
len(data)

16799

In [45]:
data[data['id']==1255558756890374144]

,Unnamed: 0,created_at,id,full_text,source,truncated,metadata,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,user,place,is_quote_status,retweet_count,favorite_count,entities,favorited,retweeted,lang
4,0,2020-04-29 18:05:09,1255558756890374144,“The Federal Reserve said the U.S. economy has...,Twitter for iPhone,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 940032448057896960, 'id_str': '94003244...",NaN,False,0,1,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en

In [46]:
data[14500:14510]

,Unnamed: 0,created_at,id,full_text,source,truncated,metadata,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,user,place,is_quote_status,retweet_count,favorite_count,entities,favorited,retweeted,lang
14500,0,2020-04-28 08:37:05,1255053411667578881,RT @RURALINDIA: Movie : The anatomy of NPAs : ...,Twitter for Android,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 973883327353532416, 'id_str': '97388332...",NaN,False,384,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14501,0,2020-04-28 08:32:36,1255052283097886720,RT @OANN: San Diego residents demand reopening...,Twitter for iPad,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 744950188557615104, 'id_str': '74495018...",NaN,False,529,0,"{'hashtags': [{'text': 'OANN', 'indices': [89,...",False,False,en
14502,0,2020-04-28 08:32:31,1255052260033216514,RT @BobPersis: @RepAdamSchiff 90% of COVID dea...,Twitter for Android,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 1090858461812801537, 'id_str': '1090858...",NaN,False,205,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14503,0,2020-04-28 08:32:18,1255052205503074306,"RT @stephphilip8: ""'YOU'RE GOING TO SEE THE EC...",Twitter Web App,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 3308193378, 'id_str': '3308193378', 'na...",NaN,False,129,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14504,0,2020-04-28 08:30:28,1255051746323333120,if u know anything about argentina’s economy c...,Twitter for iPhone,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 1075719961795006464, 'id_str': '1075719...",NaN,False,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14505,0,2020-04-28 08:30:05,1255051648822661121,RT @stengel: When Trump says we had the greate...,BizCreditCo,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 895420635878498304, 'id_str': '89542063...",NaN,False,130,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14506,0,2020-04-28 08:29:59,1255051623749095425,"RT @dkgochhayat: Thank u @nsitharaman, @ianura...",Twitter for iPhone,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 812622236, 'id_str': '812622236', 'name...",NaN,False,1,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14507,0,2020-04-28 08:29:41,1255051546259337218,@DrMannySenate you doctors who have used this ...,Twitter Web App,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,1.135626e+18,DrMannySenate,"{'id': 1482751176, 'id_str': '1482751176', 'na...",NaN,False,0,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14508,0,2020-04-28 08:29:40,1255051542232793090,RT @Tact_Investor: US vs China war will Destro...,Twitter Web App,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 1174230941725859840, 'id_str': '1174230...",NaN,False,1,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en
14509,0,2020-04-28 08:29:20,1255051460716498945,RT @BVMsDaughter: We actually stayed home for ...,Twitter for Android,False,"{'iso_language_code': 'en', 'result_type': 're...",NaN,NaN,NaN,"{'id': 1120800343963709441, 'id_str': '1120800...",NaN,False,3986,0,"{'hashtags': [], 'symbols': [], 'user_mentions...",False,False,en

In [49]:
myquery = {'id': 1255051546259337218}

mydoc = my_tweets_table.find(myquery)

for x in mydoc:
    print(x)
    break

{'_id': ObjectId('5ea9c4c217dfdac82a91bc1a'), 'id': 1255051546259337218, 'user_name': 'Alva', 'user_id': '1482751176', 'content': '@DrMannySenate you doctors who have used this virus to destroy U S jobs, economy &amp; business and violate Americans Constitutional RightsCivil Liberty’s lawyer you for lawsuits coming your way for destroying American livelihoods! It’s coming you all way!', 'created_at': '2020-04-28 08:29:41', 'location': '', 'hashtags': [], 'mentions': ['1135625824282058753'], 'in_reply_to_user_id': 1135625824282058753, 'in_reply_to_status_id': None, 'retweedt_orid_tweetID': -1, 'retweetedFrom_id': -1, 'retweetedFrom_name': 'NA', 'media': [], 'retweet': False, 'FavCount': 0, 'Orig_retweet_fav': -1, 'source': 'Twitter Web App', 'retweet_count': 0, 'lang': 'en'}

In [48]:
myquery = {}

mydoc = my_tweets_table.find(myquery)
count = 0
for x in mydoc:
    count = count + 1
print(count)

16898